"""Pydantic v2 request / response models for the FastAPI server (T1.7).

Schema layer is deliberately small — the heavy lifting is done by the
inference + SDSS modules. Models live here so OpenAPI / autogenerated
docs stay accurate as the API surface grows in T4.x (UMAP, posteriors).
"""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field

# Galaxy10 DECaLS class names (matthieulel/galaxy10_decals canonical order
# — DO NOT reorder; the trained classifier head was learned against these
# integer indices). Source: dataset card on Hugging Face Hub.
GALAXY10_LABEL_NAMES: tuple[str, ...] = (
    "disturbed",
    "merging",
    "round-smooth",
    "in-between-round-smooth",
    "cigar-shaped-smooth",
    "barred-spiral",
    "unbarred-tight-spiral",
    "unbarred-loose-spiral",
    "edge-on-no-bulge",
    "edge-on-with-bulge",
)


class _StrictResponse(BaseModel):
    model_config = ConfigDict(extra="forbid")


class HealthResponse(_StrictResponse):
    ok: bool = Field(..., description="True when the model is loaded and ready.")
    model_run_id: str = Field(..., description="run_id of the loaded checkpoint.")
    model_kind: str = Field(..., description="vit_baseline or zoobot_convnext.")
    uptime_s: float = Field(..., description="Seconds since FastAPI startup.")


class TopKItem(_StrictResponse):
    class_id: int = Field(..., ge=0, le=len(GALAXY10_LABEL_NAMES) - 1)
    class_name: str
    probability: float = Field(..., ge=0.0, le=1.0)


class PredictResponse(_StrictResponse):
    top_k: list[TopKItem] = Field(
        ..., description="Top-k softmax probabilities, sorted descending."
    )
    attention_id: str = Field(
        ...,
        description=(
            "UUID handle for the cached GradCAM overlay; fetch via "
            "GET /api/attention/{id}."
        ),
    )
