"""Pydantic v2 request / response models for the FastAPI server (T1.7).

Schema layer is deliberately small — the heavy lifting is done by the
inference + SDSS modules. Models live here so OpenAPI / autogenerated
docs stay accurate as the API surface grows in T4.x (UMAP, posteriors).
"""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field

# Galaxy10 DECaLS class names (matthieulel/galaxy10_decals canonical order
# — DO NOT reorder; the trained classifier head was learned against these
# integer indices). Source: dataset card on Hugging Face Hub.
GALAXY10_LABEL_NAMES: tuple[str, ...] = (
    "disturbed",
    "merging",
    "round-smooth",
    "in-between-round-smooth",
    "cigar-shaped-smooth",
    "barred-spiral",
    "unbarred-tight-spiral",
    "unbarred-loose-spiral",
    "edge-on-no-bulge",
    "edge-on-with-bulge",
)


class _StrictResponse(BaseModel):
    model_config = ConfigDict(extra="forbid")


class HealthResponse(_StrictResponse):
    ok: bool = Field(..., description="True when the model is loaded and ready.")
    model_run_id: str = Field(..., description="run_id of the loaded checkpoint.")
    model_kind: str = Field(..., description="vit_baseline or zoobot_convnext.")
    uptime_s: float = Field(..., description="Seconds since FastAPI startup.")


class TopKItem(_StrictResponse):
    class_id: int = Field(..., ge=0, le=len(GALAXY10_LABEL_NAMES) - 1)
    class_name: str
    probability: float = Field(..., ge=0.0, le=1.0)


class PredictResponse(_StrictResponse):
    top_k: list[TopKItem] = Field(
        ..., description="Top-k softmax probabilities, sorted descending."
    )
    attention_id: str = Field(
        ...,
        description=(
            "UUID handle for the cached GradCAM overlay; fetch via "
            "GET /api/attention/{id}."
        ),
    )


# ---------------------------------------------------------------------------
# T4.3 -- Multi-question Dirichlet posterior schemas
# ---------------------------------------------------------------------------


class PosteriorAnswerItem(_StrictResponse):
    name: str = Field(..., description="Canonical answer name (e.g. 'smooth').")
    mean: float = Field(..., ge=0.0, le=1.0, description="Posterior-mean probability.")
    ci_lower: float = Field(..., ge=0.0, le=1.0, description="95% CI lower bound.")
    ci_upper: float = Field(..., ge=0.0, le=1.0, description="95% CI upper bound.")


class PosteriorQuestionItem(_StrictResponse):
    question: str = Field(..., description="Canonical question name.")
    answers: list[PosteriorAnswerItem]
    plurality_answer: str = Field(..., description="Posterior-mean argmax answer.")
    plurality_index: int = Field(..., ge=0)
    n_effective: float = Field(
        ..., gt=0.0, description="Sum of alpha for this question (effective sample size)."
    )
    active: bool = Field(
        ...,
        description=(
            "False when the parent-dependency tree gates this question off "
            "given the model's predicted pluralities. The frontend greys "
            "out inactive questions."
        ),
    )
    parent_question: str | None = None
    parent_answer: str | None = None


class PosteriorResponse(_StrictResponse):
    questions: list[PosteriorQuestionItem]
    calibration_regime: str = Field(
        ...,
        description=(
            "'single_T' when post-hoc temperature calibration is loaded; "
            "'none' when the raw checkpoint is served."
        ),
    )
    temperature: float = Field(
        ..., gt=0.0, description="Calibration temperature applied (1.0 = none)."
    )


class DemoGalaxyItem(_StrictResponse):
    id: str = Field(..., description="Stable galaxy identifier (zero-padded index).")
    smooth_or_featured_plurality: str = Field(
        ..., description="Coarse ground-truth class from the volunteer votes."
    )
    thumbnail_url: str = Field(..., description="Relative URL of the thumbnail JPEG.")


class DemoGalaxiesResponse(_StrictResponse):
    galaxies: list[DemoGalaxyItem]


class VolunteerOverlayItem(_StrictResponse):
    """Empirical per-answer vote fractions for the compare-to-volunteers overlay."""

    question: str
    valid: bool = Field(
        ..., description="True when this question was reached by the volunteer tree."
    )
    fractions: list[float] = Field(
        ..., description="Per-answer fractions count_i / sum(counts) (0 if total = 0)."
    )


class DemoGalaxyPosteriorResponse(_StrictResponse):
    posterior: PosteriorResponse
    volunteer: list[VolunteerOverlayItem]


# ---------------------------------------------------------------------------
# T4.2 -- UMAP Explorer schemas
# ---------------------------------------------------------------------------


class UMAPPoint(_StrictResponse):
    idx: int = Field(..., ge=0, description="Row index aligned with test_thumbs/<idx>.jpg.")
    x: float
    y: float
    z: float | None = Field(
        None,
        description="A-6: third UMAP coordinate, populated only when n_dims=3.",
    )
    label: int = Field(..., ge=0, description="Coarse smooth-or-featured class id.")
    label_name: str = Field(..., description="smooth | featured-or-disk | artifact")


class UMAPPointsResponse(_StrictResponse):
    points: list[UMAPPoint]
    label_names: list[str] = Field(
        ..., description="Ordered class names; index = label id."
    )


# ---------------------------------------------------------------------------
# S-1 -- Similar-galaxy kNN schemas
# ---------------------------------------------------------------------------


class SimilarGalaxyItem(_StrictResponse):
    idx: int = Field(
        ...,
        ge=0,
        description="Row index aligned with test_thumbs/<idx>.jpg.",
    )
    distance: float = Field(
        ...,
        ge=0.0,
        le=2.0,
        description="Cosine distance from query (0 = identical, 2 = opposite).",
    )
    thumbnail_url: str = Field(
        ..., description="Relative URL of the matching test thumbnail."
    )


class SimilarGalaxiesResponse(_StrictResponse):
    query_idx: int | None = Field(
        None,
        description=(
            "Cache row index used as the query, when the request came via "
            "GET /api/similar/{idx}. Null for POST /api/similar uploads."
        ),
    )
    hits: list[SimilarGalaxyItem] = Field(
        ...,
        description="Top-K nearest neighbours, ascending by cosine distance.",
    )


# ---------------------------------------------------------------------------
# S-3 -- Outlier ("most interesting galaxies") schemas
# ---------------------------------------------------------------------------


class OutlierItem(_StrictResponse):
    idx: int = Field(
        ...,
        ge=0,
        description="Row index aligned with test_thumbs/<idx>.jpg.",
    )
    value: float = Field(
        ...,
        description=(
            "Metric value (entropy / BALD / disagreement). Higher = more "
            "outlier-y. Sorted descending across the response list."
        ),
    )
    thumbnail_url: str = Field(
        ..., description="Relative URL of the matching test thumbnail."
    )


class OutliersResponse(_StrictResponse):
    metric: str = Field(
        ...,
        description="One of: entropy | bald | disagreement.",
    )
    median: float = Field(
        ...,
        description=(
            "Population median of the requested metric (across all 2,462 "
            "galaxies, or the volunteer-voted subset for 'disagreement')."
        ),
    )
    items: list[OutlierItem] = Field(
        ...,
        description="Top-K outliers, descending by metric value.",
    )


# ---------------------------------------------------------------------------
# S-2 -- Sky map schemas
# ---------------------------------------------------------------------------


class SkyPoint(_StrictResponse):
    dr8_id: str = Field(..., description="DESI Legacy Survey DR8 identifier.")
    ra: float = Field(..., ge=0.0, le=360.0, description="Right ascension (degrees).")
    dec: float = Field(..., ge=-90.0, le=90.0, description="Declination (degrees).")
    label: int = Field(
        ..., ge=0, description="Argmax over the smooth-or-featured posterior mean."
    )
    label_name: str = Field(..., description="smooth | featured-or-disk | artifact")
    entropy: float = Field(
        ...,
        ge=0.0,
        description="Predictive entropy summed across the 10 GZ DESI questions.",
    )


class SkyPointsResponse(_StrictResponse):
    points: list[SkyPoint]
    label_names: list[str] = Field(
        ..., description="Ordered class names; index = label id."
    )
